seed: 42
dataset: PDB
dataset_download_dir: /home/arin/mind-molecular-intelligence/data
out_path: /home/arin/mind-molecular-intelligence/outputs/pdb_pretrain
wandb_project_name: esa-pretraining
wandb_run_name: pretraining-PDB-protein-yaml
max_epochs: 200
gradient_clip_val: 0.5
monitor_loss_name: train_total_loss

num_workers: 4

protein_max_residues: 500

apply_attention_on: node
num_features: 128
graph_dim: 256
edge_dim: 64
hidden_dims: [256, 256, 256, 256]
num_heads: [8, 8, 8, 8]
layer_types: ["M", "M", "S", "P"]
xformers_or_torch_attn: torch
norm_type: LN
use_3d_coordinates: true

gaussian_kernels: 128
cutoff_distance: 6.0
max_neighbors: 64

use_bfloat16: false

pretraining_tasks: ["coordinate_denoising", "mlm", "contrastive","distance_prediction"]
task_weights:
  coordinate_denoising: 1.0
  mlm: 1.0
  contrastive: 0.5
  distance_prediction: 0.5

coordinate_noise_std: 0.1
mlm_mask_ratio: 0.15
temperature: 0.2

lr: 0.0001
early_stopping_patience: 30
optimiser_weight_decay: 0.0000000001

batch_size: 10


